### PR TITLE
refactor(gce): convert ava tests to mocha

### PR DESCRIPTION
**Pull request by nareshqlogic**
Fixes convert tests from ava to mocha #254 (it's a good idea to open an issue first for discussion)

### CODE REVIEW

**Comment by fhinkel** [comment]
Please fix the linter issues.

**Comment by nareshqlogic** [comment]
Hi @fhinkel ,
Someone already fixed linter error in master branch. So I merged that change. Please check and let me know still you are able to see errors. Please keep posting error as I don't have rights see logs.Thank you for letting me know error as a comment.

**Comment by fhinkel** [comment]
@nareshqlogic please resolve the merge conflicts. Feel free to land where approved and all tests passing. Thanks

**Comment by fhinkel** [comment]
Closing this due to inactivity. Feel free to reopen as you work on it.

**Pull request closed without merging**
