### PR TITLE
refactor(structured-data): convert ava tests to mocha

### PR DESCRIPTION
**Pull request by nareshqlogic**
Fixes convert tests from ava to mocha [#254](https://github.com/GoogleCloudPlatform/nodejs-getting-started/issues/254) (it's a good idea to open an issue first for discussion)

### CODE REVIEW

**Comment by nareshqlogic** [comment]
Hi @fhinkel,
I am unable to assign anyone as a reviewer. Can you please look over the pr?

**Comment by fhinkel** [comment]
Thanks. Tests are unhappy about this: 

```
ok 73 - 3-binary-data › test › app › should check config
/tmpfs/src/github/nodejs-getting-started/2-structured-data/test/cloudsql.test.js:22
  it('Skipping Cloud SQL tests...', () => assert.ok(true));
  ^

ReferenceError: it is not defined
    at Object.it (/tmpfs/src/github/nodejs-getting-started/2-structured-data/test/cloudsql.test.js:25:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at extensions.(anonymous function) (/tmpfs/src/github/nodejs-getting-started/node_modules/require-precompiled/index.js:13:11)
    at Object.require.extensions.(anonymous function) [as .js] (/tmpfs/src/github/nodejs-getting-started/node_modules/ava/lib/process-adapter.js:100:4)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/tmpfs/src/github/nodejs-getting-started/node_modules/ava/lib/test-worker.js:62:1)
# 2-structured-data/test/cloudsql.test.js exited with a non-zero exit code: 1
not ok 74 - 2-structured-data/test/cloudsql.test.js exited with a non-zero exit code: 1

1..72
# tests 72
# pass 72
# fail 2
```

**Comment by nareshqlogic** [comment]
Hi @fhinkel ,
I can see these test are running with AVA test framework referencing to 3-binary-data test folder  ( ok 73 - 3-binary-data › test › app › should check config) and that is different one as we are here working on 2-structured-data folder and also updated package.json file with mocha. 
Can you please recheck after npm install command in 2-structured-data folder only as we have created separate PR for each of library. Thanks.

**Comment by fhinkel** [comment]
Hi, there error is here: `/tmpfs/src/github/nodejs-getting-started/2-structured-data/test/cloudsql.test.js:22
  it('Skipping Cloud SQL tests...', () => assert.ok(true));`. Is that not the files that you've been changing? The tests run `npm install` on a new checkout.

**Comment by fhinkel** [comment]
The presubmit tests run this script: https://github.com/GoogleCloudPlatform/nodejs-getting-started/blob/master/.kokoro/presubmit/cloudsql.sh, which run `npm test` in the parent folder. Can you change that command to use `mocha` for `2-structured-data` but `ava` for the remaining tests. I don't want to land the PRs while the CI is red. Thanks.

**Comment by nareshqlogic** [comment]
Hi @fhinkel ,

I fixed the presubmit tests issue. Can you please check now?

**Comment by nareshqlogic** [comment]
Hi @fhinkel,

I don't have rights to apply label kokoro:run or view log. Can you please post the error in comment.

**Comment by fhinkel** [comment]
This was the error: 

```
> nodejs-getting-started@1.0.0 mocha /tmpfs/src/github/nodejs-getting-started
> mocha "**/2-structured-data/test/!(datastore).test.js"  --timeout=30000



  ✓ should redirect / to /books (681ms)
  ✓ should check config (41ms)
2019/01/30 21:51:04 New connection for "nodejs-getting-started-tests:us-central1:integration-test-instance"
  ✓ should create a book (872ms)
  ✓ should list books (53ms)
  ✓ should delete a book (58ms)
  ✓ should create a book (95ms)
  ✓ should show a list of books (310ms)
  ✓ should handle error (71ms)
Error: ER_SP_UNDECLARED_VAR: Undeclared variable: NaN
    at Query.Sequence._packetToError (/tmpfs/src/github/nodejs-getting-started/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/tmpfs/src/github/nodejs-getting-started/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/tmpfs/src/github/nodejs-getting-started/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/tmpfs/src/github/nodejs-getting-started/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/tmpfs/src/github/nodejs-getting-started/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/tmpfs/src/github/nodejs-getting-started/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/tmpfs/src/github/nodejs-getting-started/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
    --------------------
    at Protocol._enqueue (/tmpfs/src/github/nodejs-getting-started/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/tmpfs/src/github/nodejs-getting-started/node_modules/mysql/lib/Connection.js:200:25)
    at Object.list (/tmpfs/src/github/nodejs-getting-started/2-structured-data/books/model-cloudsql.js:38:14)
    at router.get (/tmpfs/src/github/nodejs-getting-started/2-structured-data/books/crud.js:40:14)
    at Layer.handle [as handle_request] (/tmpfs/src/github/nodejs-getting-started/node_modules/express/lib/router/layer.js:95:5)
    at next (/tmpfs/src/github/nodejs-getting-started/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/tmpfs/src/github/nodejs-getting-started/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/tmpfs/src/github/nodejs-getting-started/node_modules/express/lib/router/layer.js:95:5)
    at /tmpfs/src/github/nodejs-getting-started/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/tmpfs/src/github/nodejs-getting-started/node_modules/express/lib/router/index.js:335:12)
    at next (/tmpfs/src/github/nodejs-getting-started/node_modules/express/lib/router/index.js:275:10)
    at router.use (/tmpfs/src/github/nodejs-getting-started/2-structured-data/books/crud.js:31:3)
    at Layer.handle [as handle_request] (/tmpfs/src/github/nodejs-getting-started/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/tmpfs/src/github/nodejs-getting-started/node_modules/express/lib/router/index.js:317:13)
    at /tmpfs/src/github/nodejs-getting-started/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/tmpfs/src/github/nodejs-getting-started/node_modules/express/lib/router/index.js:335:12)
    at next (/tmpfs/src/github/nodejs-getting-started/node_modules/express/lib/router/index.js:275:10)
    at urlencodedParser (/tmpfs/src/github/nodejs-getting-started/node_modules/body-parser/lib/types/urlencoded.js:91:7)
    at Layer.handle [as handle_request] (/tmpfs/src/github/nodejs-getting-started/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/tmpfs/src/github/nodejs-getting-started/node_modules/express/lib/router/index.js:317:13)
    at /tmpfs/src/github/nodejs-getting-started/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/tmpfs/src/github/nodejs-getting-started/node_modules/express/lib/router/index.js:335:12)
    at next (/tmpfs/src/github/nodejs-getting-started/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/tmpfs/src/github/nodejs-getting-started/node_modules/express/lib/router/index.js:174:3)
    at router (/tmpfs/src/github/nodejs-getting-started/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/tmpfs/src/github/nodejs-getting-started/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/tmpfs/src/github/nodejs-getting-started/node_modules/express/lib/router/index.js:317:13)
    at /tmpfs/src/github/nodejs-getting-started/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/tmpfs/src/github/nodejs-getting-started/node_modules/express/lib/router/index.js:335:12)
    at next (/tmpfs/src/github/nodejs-getting-started/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/tmpfs/src/github/nodejs-getting-started/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/tmpfs/src/github/nodejs-getting-started/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/tmpfs/src/github/nodejs-getting-started/node_modules/express/lib/router/index.js:317:13)
    at /tmpfs/src/github/nodejs-getting-started/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/tmpfs/src/github/nodejs-getting-started/node_modules/express/lib/router/index.js:335:12)
    at next (/tmpfs/src/github/nodejs-getting-started/node_modules/express/lib/router/index.js:275:10)
    at query (/tmpfs/src/github/nodejs-getting-started/node_modules/express/lib/middleware/query.js:45:5)
    at Layer.handle [as handle_request] (/tmpfs/src/github/nodejs-getting-started/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/tmpfs/src/github/nodejs-getting-started/node_modules/express/lib/router/index.js:317:13)
    at /tmpfs/src/github/nodejs-getting-started/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/tmpfs/src/github/nodejs-getting-started/node_modules/express/lib/router/index.js:335:12)
    at next (/tmpfs/src/github/nodejs-getting-started/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/tmpfs/src/github/nodejs-getting-started/node_modules/express/lib/router/index.js:174:3)
    at Function.handle (/tmpfs/src/github/nodejs-getting-started/node_modules/express/lib/application.js:174:10)
    at Server.app (/tmpfs/src/github/nodejs-getting-started/node_modules/express/lib/express.js:39:9)
    at Server.emit (events.js:189:13)
    at parserOnIncoming (_http_server.js:672:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
  ✓ should post to add book form (147ms)
  ✓ should show add book form (50ms)
  ✓ should update a book (240ms)
  ✓ should show edit book form (87ms)
  ✓ should show a book (80ms)
  ✓ should delete a book (54ms)

  14 passing (3s)



ERROR: Aborting VM command due to timeout of 10800 seconds
```

**Comment by fhinkel** [comment]
@nareshqlogic please resolve the merge conflicts. Feel free to land where approved and all tests passing. Thanks

**Comment by fhinkel** [comment]
ping @nareshqlogic

**Comment by nareshqlogic** [comment]
Hi @fhinkel ,
I am unable to produce same error in my system. Please suggest your view for generating same error .

**Comment by fhinkel** [comment]
You can follow the steps in the build.sh file in `.kokoro`. Those detail the setup.

**Comment by fhinkel** [comment]
Closing due to inactivity.

**Pull request closed without merging**
