### PR TITLE
fix: update usage of @google-cloud/storage

### PR DESCRIPTION
**Pull request by parzhitsky**
Update usage of `@google-cloud/storage` after breaking #393

### CODE REVIEW

**Comment by parzhitsky** [comment]
@googlebot I signed it!

**Comment by fhinkel** [comment]
👋 @parzhitsky Thanks for this bug fix! I don't have permission to update your branch. Can you rebase it with master so we can merge it? Thank you!

**Comment by parzhitsky** [comment]
Thanks! Sure, just did it

**Comment by parzhitsky** [comment]
GitHub UI did merge instead of rebase. Do you want me to do a rebase specifically, or merge will do?

**Comment by fhinkel** [comment]
Awesome, running tests and then we can merge this 🎉

**Comment by parzhitsky** [comment]
Perfect 😀

**Comment by fhinkel** [comment]
Looks like there's a small issue with the linter: 

```
> nodejs-getting-started@ lint /tmpfs/src/github/nodejs-getting-started
> eslint '**/*.js'


/tmpfs/src/github/nodejs-getting-started/bookshelf/lib/images.js
  20:8  error  Replace `·Storage·` with `Storage`  prettier/prettier

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
```

**Pull request merged**
