### PR TITLE
Skip yarn lockfiles in GAE deploys

### PR DESCRIPTION
**Pull request by ace-n**
A non-forked copy of #130

### CODE REVIEW

**Comment by phillipj** [comment]
Did you consider deleting `yarn.lock` from the repo entirely? As noted in https://github.com/GoogleCloudPlatform/nodejs-getting-started/issues/129, it's not obvious to me why we should keep a lockfile around that will get ignored when building anyways..

**Comment by ace-n** [comment]
Our instructions [still mention yarn](https://cloud.google.com/nodejs/getting-started/using-cloud-datastore#installing_dependencies). That can be changed of course - but would require additional work + research.

**Comment by phillipj** [comment]
Valid point.

Food for thought, if a dev uses yarn locally while following those instructions, might even install new dependencies, npm will be used when building in the cloud since yarns lockfile is ignored 🙁

**Comment by jmdobry** [comment]
I'm in favor of deleting the lock files from the repo entirely.

**Comment by phillipj** [comment]
Agreed, that sounds like the way to go. If there's no lockfiles present when installing packages listed in `package.json`, both npm and yarn will create lockfiles after all dependencies has been installed. Therefore no need to ignore any lockfile in `app.yaml` since only one of them will be present, and that lockfile will also be used when building -- sounds like great success to me.

**Comment by ace-n** [comment]
Cool. I'll close these PRs and make this change in #124 (since this is blocking that PR, and #124 is almost - but not quite - finished).

**Pull request closed without merging**
