### PR TITLE
Switch 1-hello-world runtime to nodejs

### PR DESCRIPTION
**Pull request by TEHEK**

### CODE REVIEW

**Comment by jonparrott** [comment]
Can you leave the dockerfile and explicitly use the gcr.io image?

**Comment by TEHEK** [comment]
Ok, let me test it first.

By the way, do I need update images in other branches as well?

**Comment by jonparrott** [comment]
I can handle that.

**Comment by TEHEK** [comment]
Looks like keeping the Dockerfile causes an error:

ERROR: (gcloud.preview.app.deploy)  Deployed Version: <some numbers here>

**Comment by jonparrott** [comment]
Is there more to the error? We should be able to have a Dockerfile just like all of the other runtimes.

**Comment by jonparrott** [comment]
@TEHEK see commit 614724b, seems to work here and deploy fine. I generated the Dockerfile using gcloud preview app gen-config.

**Pull request closed without merging**
