### PR TITLE
changed the callback event from complete to finish in branch 3

### PR DESCRIPTION
**Pull request by thalesmello**
I had problems in this part of the tutorial, because the callback event is wrong.

There is a [StackOverflow post](http://stackoverflow.com/questions/32380263/cant-connect-to-the-storage-server-in-the-google-compute-engine-tutorial-for-no) in which I detail the problem and the solution that I found.

This PR aims to fix this.

### CODE REVIEW

**Comment by jonparrott** [comment]
Thanks, it seems some behavior changed in the gcloud node library. Before I can merge this, I unfortunately need to you sign our [Contributor License Agreement](https://cla.developers.google.com/clas).

I closed the other PRs as this one is the only one that's needed. The patch to this one will be applied to the other branches via a script.

**Comment by thalesmello** [comment]
I just signed the term. Is there anything else to do?

**Comment by jonparrott** [comment]
That's it! I'll merge once I get a chance to test it.

Thank you for your contribution!

**Comment by jonparrott** [comment]
@thalesmello I couldn't reproduce this locally. Can you hop over to [https://github.com/GoogleCloudPlatform/gcloud-node/issues/849](https://github.com/GoogleCloudPlatform/gcloud-node/issues/849) and share some information?

**Pull request closed without merging**
