### PR TITLE
refactor(optional kubernetes engine): convert ava tests to mocha

### PR DESCRIPTION
**Pull request by nareshqlogic**
Fixes convert tests from ava to mocha #254 (it's a good idea to open an issue first for discussion)

### CODE REVIEW

**Comment by fhinkel** [comment]
The linter has issues. Can you run `npm run lint -- --fix` in the parent directory. Thanks.

```
> nodejs-getting-started@1.0.0 test /tmpfs/src/github/nodejs-getting-started
> npm run lint && npm run ava


> nodejs-getting-started@1.0.0 lint /tmpfs/src/github/nodejs-getting-started
> eslint '**/*.js'


/tmpfs/src/github/nodejs-getting-started/7-gce/books/model-mongodb.js
  44:23  error  Replace `⏎····config.get('MONGO_URL'),⏎···` with `config.get('MONGO_URL'),`  prettier/prettier
  47:1   error  Delete `··`                                                                  prettier/prettier
  48:7   error  Delete `··`                                                                  prettier/prettier
  49:1   error  Replace `········` with `······`                                             prettier/prettier
  50:5   error  Delete `··`                                                                  prettier/prettier
  51:1   error  Delete `··`                                                                  prettier/prettier
  52:1   error  Delete `··`                                                                  prettier/prettier
  53:5   error  Delete `··`                                                                  prettier/prettier
  54:3   error  Replace `··}⏎··` with `}`                                                    prettier/prettier

/tmpfs/src/github/nodejs-getting-started/optional-kubernetes-engine/books/model-mongodb.js
  44:23  error  Replace `⏎····config.get('MONGO_URL'),⏎···` with `config.get('MONGO_URL'),`  prettier/prettier
  47:1   error  Delete `··`                                                                  prettier/prettier
  48:7   error  Delete `··`                                                                  prettier/prettier
  49:1   error  Replace `········` with `······`                                             prettier/prettier
  50:5   error  Delete `··`                                                                  prettier/prettier
  51:1   error  Delete `··`                                                                  prettier/prettier
  52:1   error  Delete `··`                                                                  prettier/prettier
  53:5   error  Delete `··`                                                                  prettier/prettier
  54:3   error  Replace `··}⏎··` with `}`                                                    prettier/prettier

✖ 18 problems (18 errors, 0 warnings)
  18 errors and 0 warnings potentially fixable with the `--fix` option.
```

**Comment by nareshqlogic** [comment]
Hi @fhinkel ,
Someone already fixed linter error in master branch. So I merged that change. Please check and let me know still you are able to see errors. Please keep posting error as I don't have rights see logs.Thank you for letting me know error as a comment.

**Comment by fhinkel** [comment]
Sorry about the linter issues on master. Running the tests again...

**Comment by fhinkel** [comment]
@nareshqlogic please resolve the merge conflicts. Feel free to land where approved and all tests passing. Thanks

**Comment by fhinkel** [comment]
Closing this due to inactivity. Feel free to reopen as you work on it.

**Pull request closed without merging**
